### ISSUE TITLE
url.searchParams.sort is not a function

### ISSUE THREAD

**Issue by BingxuJ** [swestmoreland/scormcloud-api-wrapper#1]
Hello,

Currently, I am having the issue in url.searchParams.sort function. Can someone suggest how to solve the issue? Thanks.

------------------------------------This is the error message---------------------------------
scormcloud.js:1183
    url.searchParams.sort();
TypeError: url.searchParams.sort is not a function

**Comment by swestmoreland** [comment]
Which version of Node.js are you using?

**Comment by BingxuJ** [comment]
Okay. Thanks. I am using node 7.6.0 now. I will try 7.7.0 version.

**Comment by swestmoreland** [comment]
You should now receive a warning when installing the package with node < 7.7.0 – Thanks for reporting this issue.
