### ISSUE TITLE
TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by bocodigital** [swestmoreland/scormcloud-api-wrapper#2]
scormcloud-api-wrapper/src/scormcloud.js:162:15

I tried installing url as it was not set as a dependency but its still doesn't work.

**Comment by bocodigital** [comment]
withdrawn I was just using a really old version of node

**Comment by Trescend** [comment]
have the same problem but installing new version node.js doesn't fix it.
How did you fixed it?
BTW i'm using Meteor.
