### ISSUE TITLE
i got "TypeError: URL is not a constructor"

### ISSUE THREAD

**Issue by Trescend** [swestmoreland/scormcloud-api-wrapper#3]
How to fix this?
I'm using Meteor 1.7.0.3
Node 8.11.4

**Comment by swestmoreland** [comment]
Are you using this module in a browser environment? This module is meant to be used with the Node.js runtime -- e.g. `node myModule.js`. Have you tried the [steps described here](https://stevenwestmoreland.com/2017/11/nodejs-client-for-scormcloud-api.html#usage) to construct the API client, verify that your credentials are valid and that the web service is reachable?
