### ISSUE TITLE
setCourseAttributes

### ISSUE THREAD

**Issue by springcode** [swestmoreland/scormcloud-api-wrapper#6]
api.setCourseAttributes(courseId, {"scoLaunchType":1,"playerLaunchType":1}, function(error, result) {
  //
});

TypeError: Cannot read property 'forEach' of undefined when trying to set an attribute.

json.rsp = {stat: "ok", attributes: ""} 

Attributes is blank hence the forEach fails.   
        attributes.forEach(function (attribute) {
            data[attribute.name] = getCourseAttributeValue(attribute.name, attribute.value);
        });

Is this an issue with Rustici Api not returning the attribute list?  The attributes seems to be set in the SCORMCloud ok.

**Comment by swestmoreland** [comment]
Resolved in 1.1.11
